head:
  samples:
    samples/head/test/all_face: head_all_face
    samples/head/test/negative: head_negative
  images: output/temp/head_testing
  script: output/scripts
  forests: output/forests/head
  type: output/results

body1:
  samples:
    test/body1: body1
  
