head:
  samples:
    samples/head_test/all_face: head_all_face
    samples/head_test/negative: head_negative
  images: output/temp/head_testing
  script: output/scripts
  forests: output/forests/head
  results: output/test/results
  types: output/test/results

body1:
  samples:
    test/body1: body1
  
