head:
  samples:
    samples/head/test/all_face: head_all_face
    samples/head/test/negative: head_negative
  pixel_info: I
  tables: output/head/datasets
  script: output/head/scripts
  forest: output/head/forests

body1:
  samples:
    test/body1: body1
  
