head1:
  samples:
    test/sample_out: head1
    test/negative_out: negative_head1
  tables: test/datasets
  script: test/scripts
  forest: test/forests
  trees: 100


body1:
  samples:
    test/body1: body1
  
